// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOBlNaj3G6TCn5bqFpFjqNB3Q_p3suEb0',
    appId: '1:869536082400:web:91af225032934d5d776385',
    messagingSenderId: '869536082400',
    projectId: 'wastereports-c60b8',
    authDomain: 'wastereports-c60b8.firebaseapp.com',
    storageBucket: 'wastereports-c60b8.appspot.com',
    measurementId: 'G-FJXL2LCWCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWEcVgB2MAnDcpyO2h45Jjxkn0e2Zm44',
    appId: '1:869536082400:android:fed54f44329bc77e776385',
    messagingSenderId: '869536082400',
    projectId: 'wastereports-c60b8',
    storageBucket: 'wastereports-c60b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW7X33YrP_YSmMfatag1dPAenFO8HNV_M',
    appId: '1:869536082400:ios:31ab62af2c96468b776385',
    messagingSenderId: '869536082400',
    projectId: 'wastereports-c60b8',
    storageBucket: 'wastereports-c60b8.appspot.com',
    iosBundleId: 'com.example.wasteGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW7X33YrP_YSmMfatag1dPAenFO8HNV_M',
    appId: '1:869536082400:ios:31ab62af2c96468b776385',
    messagingSenderId: '869536082400',
    projectId: 'wastereports-c60b8',
    storageBucket: 'wastereports-c60b8.appspot.com',
    iosBundleId: 'com.example.wasteGo',
  );

}